/*
  compareMetrics.js — the metric registry for the Company Comparison builder
  (Atlas Section 08).

  Pickers are driven by DATA, not by this file's wishes: coverage() counts,
  for any ticker set, how many companies actually have a figure for a metric.
  A metric with zero coverage never appears in the picker. Nothing here
  invents a figure — every value is resolved live from kpis.json (12
  companies) or comparison.json (NVDA/AMD-only verified extras).

  Explanation layers: `explain` carries the three company-agnostic layers
  (what / why / good). The fourth layer ("what this result means") is
  generated by describeGap() from the live selection — deterministic,
  banned-vocabulary-free.

  Banned vocabulary (never in any string below): buy, sell, undervalued,
  overvalued, cheap, expensive, should, recommend, target, poised, set to.
*/
import { kpisByTicker, comparison } from './data.js'
import { parseScalar } from './compareVisual.js'

export const FAMILIES = [
  { id: 'size', label: 'Size & scale' },
  { id: 'valuation', label: 'Valuation' },
  { id: 'growth', label: 'Growth' },
  { id: 'profitability', label: 'Profitability' },
  { id: 'returns', label: 'Returns on capital' },
  { id: 'balance', label: 'Balance sheet' },
  { id: 'cash', label: 'Cash generation' },
  { id: 'market', label: 'Market behavior' },
  { id: 'cloud', label: 'Cloud & backlog' },
  { id: 'company', label: 'Company-specific' },
]

/*
  Each def:
    id            canonical id
    label         picker label
    family        family id
    visual        'bar' | 'scale' | 'chips'   (profitability also gets
                  diverging bars when exactly 2 companies are selected)
    higherIsBetter true | false | null (null = no ▲ marking, e.g. multiples)
    sources       list of { kind: 'kpis', label } or { kind: 'kpis', perTicker: {T:'label'} }
                  or { kind: 'comparison', label } (NVDA/AMD-only verified extras)
    explain       { what, why, good }
*/
export const METRICS = [
  // ---------------- Size & scale ----------------
  {
    id: 'revenue', label: 'Revenue', family: 'size', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Revenue' }],
    explain: {
      what: 'Total sales over the fiscal year.',
      why: 'The top line everything else is built from — growth here funds R&D, capex, and hiring.',
      good: 'Steady double-digit growth is strong for large caps; sustained 30%+ is rare.',
    },
  },
  {
    id: 'latest-quarter', label: 'Latest quarter revenue', family: 'size', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Latest quarter' }],
    explain: {
      what: 'Revenue in the most recently reported quarter.',
      why: 'The freshest read on momentum — inflections in growth show here before they show in the full year.',
      good: 'Judge against the year-ago quarter, not the prior quarter; seasonality moves single quarters around.',
    },
  },
  {
    id: 'market-cap', label: 'Market capitalization', family: 'size', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Market capitalization' }, { kind: 'comparison', label: 'Market capitalization' }],
    explain: {
      what: 'Share price times shares outstanding — what the market says the whole company is worth.',
      why: 'The scoreboard of expectations: it prices future growth, not just current profit.',
      good: 'There is no good absolute level — it only means something relative to earnings, sales, or peers.',
    },
  },
  {
    id: 'ev', label: 'Enterprise value', family: 'size', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Enterprise value' }, { kind: 'comparison', label: 'Enterprise value' }],
    explain: {
      what: "Market cap plus debt minus cash — the price of buying the whole business, debt and all.",
      why: 'Cleaner than market cap for comparing companies with different debt loads.',
      good: 'Near-identical to market cap means the company carries almost no net debt.',
    },
  },
  // ---------------- Valuation ----------------
  {
    id: 'pe-trailing', label: 'P/E ratio (trailing)', family: 'valuation', visual: 'scale', higherIsBetter: null,
    sources: [{ kind: 'kpis', label: 'P/E ratio (trailing)' }, { kind: 'comparison', label: 'P/E ratio (trailing)' }],
    explain: {
      what: 'Price divided by last twelve months of earnings per share.',
      why: 'How many dollars the market pays per dollar of current earnings — a shorthand for growth expectations.',
      good: 'A high multiple prices in fast future growth; a low one prices in stagnation. Neither is a verdict on its own.',
    },
  },
  {
    id: 'ps', label: 'Price / sales', family: 'valuation', visual: 'scale', higherIsBetter: null,
    sources: [{ kind: 'kpis', label: 'Price / sales' }, { kind: 'comparison', label: 'Price / sales' }],
    explain: {
      what: 'Market cap divided by annual revenue.',
      why: 'Useful when earnings are thin or negative — values the sales engine directly.',
      good: 'Means little alone; compare against the peer set and against profit margins.',
    },
  },
  {
    id: 'pfcf', label: 'Price / free cash flow', family: 'valuation', visual: 'scale', higherIsBetter: null,
    sources: [{ kind: 'kpis', label: 'Price / free cash flow' }, { kind: 'comparison', label: 'Price / free cash flow' }],
    explain: {
      what: 'Market cap divided by free cash flow.',
      why: 'Prices the cash the business actually generates, sidestepping accounting choices in earnings.',
      good: 'Lower means more cash per dollar of price — but fast growers nearly always carry higher multiples.',
    },
  },
  {
    id: 'eps-diluted', label: 'Diluted EPS', family: 'valuation', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Diluted EPS' }],
    explain: {
      what: 'Profit per share, counting all potential shares outstanding.',
      why: 'The per-share number markets price off — growth here is what shareholders actually feel.',
      good: 'Growing faster than revenue is the ideal pattern: margin expansion plus buybacks working together.',
    },
  },
  // ---------------- Growth ----------------
  {
    id: 'rev-growth-1y', label: 'Revenue growth (1Y)', family: 'growth', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Revenue growth (1Y)' }, { kind: 'comparison', label: 'Revenue growth (1Y)' }],
    explain: {
      what: 'Year-over-year change in annual revenue.',
      why: 'The single fastest read on whether the business is accelerating or stalling.',
      good: 'Double digits is healthy for large caps; triple digits usually reflects a one-time demand wave.',
    },
  },
  {
    id: 'rev-cagr-5y', label: 'Revenue CAGR (5Y)', family: 'growth', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Revenue CAGR (5Y)' }, { kind: 'comparison', label: 'Revenue CAGR (5Y)' }],
    explain: {
      what: 'Compound annual growth rate of revenue over five years.',
      why: 'Smooths single-year spikes — shows the durable growth engine, not one hot cycle.',
      good: 'Sustained 20%+ over five years at scale is exceptional.',
    },
  },
  // ---------------- Profitability ----------------
  {
    id: 'gross-margin', label: 'Gross margin', family: 'profitability', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Gross margin' }],
    explain: {
      what: 'Share of each sales dollar left after the cost of making the product.',
      why: 'The clearest read on pricing power — high margin means customers pay far above production cost.',
      good: '45–60% is typical for chip designers; above 65% signals unusual pricing power.',
    },
  },
  {
    id: 'op-margin', label: 'Operating margin', family: 'profitability', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Operating margin' }],
    explain: {
      what: 'Share of revenue left after operating costs — R&D, sales, administration.',
      why: 'Shows whether the business model scales: rising operating margin means growth is getting more efficient.',
      good: '30%+ is elite for tech; negative means the model does not yet pay for itself.',
    },
  },
  {
    id: 'net-income', label: 'Net income', family: 'profitability', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Net income' }],
    explain: {
      what: 'Profit left after all costs, taxes, and interest.',
      why: 'The bottom line — what the business actually kept for shareholders.',
      good: 'Positive and growing; as a margin, 15–25% is strong for large tech.',
    },
  },
  {
    id: 'net-margin', label: 'Net margin', family: 'profitability', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Net margin' }, { kind: 'comparison', label: 'Net margin' }],
    explain: {
      what: 'Net income as a share of revenue.',
      why: 'Compresses the whole P&L into one number — how much of each sale survives to the bottom.',
      good: 'Above 20% is strong; above 40% is found almost only in software-like or monopoly-positioned businesses.',
    },
  },
  {
    id: 'rnd', label: 'R&D spend', family: 'profitability', visual: 'bar', higherIsBetter: null,
    sources: [{ kind: 'kpis', label: 'R&D spend' }],
    explain: {
      what: 'Annual investment in research and development.',
      why: 'For chip and cloud companies, R&D is the moat factory — it buys the next product cycle.',
      good: '8–15% of revenue is typical for semis; hyperscalers spend far more in absolute dollars.',
    },
  },
  // ---------------- Returns on capital ----------------
  {
    id: 'roe', label: 'Return on equity (ROE)', family: 'returns', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Return on equity (ROE)' }, { kind: 'comparison', label: 'Return on equity (ROE)' }],
    explain: {
      what: 'Net income divided by shareholder equity — profit per dollar of owners’ capital.',
      why: 'Measures how hard management works the capital entrusted to it.',
      good: 'Sustained 15%+ is strong; very high readings can reflect buybacks shrinking equity, not just profit.',
    },
  },
  {
    id: 'roa', label: 'Return on assets (ROA)', family: 'returns', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Return on assets (ROA)' }, { kind: 'comparison', label: 'Return on assets (ROA)' }],
    explain: {
      what: 'Net income divided by total assets.',
      why: 'Harder to flatter than ROE — shows how productively the whole asset base is used.',
      good: 'Above 10% is strong for asset-heavy businesses; asset-light models run much higher.',
    },
  },
  // ---------------- Balance sheet ----------------
  {
    id: 'net-debt', label: 'Net debt', family: 'balance', visual: 'bar', higherIsBetter: false,
    sources: [{ kind: 'kpis', label: 'Net debt' }, { kind: 'comparison', label: 'Net debt' }],
    explain: {
      what: 'Total debt minus cash and equivalents — negative means net cash.',
      why: 'Net cash is strategic freedom: acquisitions, buybacks, and surviving downturns without borrowing.',
      good: 'Net cash or low net debt relative to earnings; watch it when it starts climbing fast.',
    },
  },
  {
    id: 'debt-equity', label: 'Debt / equity', family: 'balance', visual: 'bar', higherIsBetter: false,
    sources: [{ kind: 'kpis', label: 'Debt / equity' }, { kind: 'comparison', label: 'Debt / equity' }],
    explain: {
      what: 'Total debt divided by shareholder equity.',
      why: 'Leverage gauge — how much of the business is funded by borrowing versus owners’ capital.',
      good: 'Below 0.5 is conservative for tech; rising ratios ahead of a downturn deserve attention.',
    },
  },
  {
    id: 'cash', label: 'Cash & equivalents', family: 'balance', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Cash & equivalents' }, { kind: 'comparison', label: 'Cash & equivalents' }],
    explain: {
      what: 'Cash plus short-term investments on the balance sheet.',
      why: 'Dry powder — funds buybacks, deals, and R&D through cycles without tapping markets.',
      good: 'Large relative to annual capex and buybacks; hoarding far beyond needs can signal a lack of ideas.',
    },
  },
  // ---------------- Cash generation ----------------
  {
    id: 'ocf', label: 'Operating cash flow', family: 'cash', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Operating cash flow' }, { kind: 'kpis', label: 'Op cash flow' }, { kind: 'comparison', label: 'Operating cash flow' }],
    explain: {
      what: 'Cash generated by running the business, before investing or financing.',
      why: 'The reality check on reported profit — persistent gaps between cash flow and net income deserve questions.',
      good: 'Should track above net income over time as non-cash charges add back.',
    },
  },
  {
    id: 'fcf', label: 'Free cash flow', family: 'cash', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Free cash flow' }, { kind: 'comparison', label: 'Free cash flow' }],
    explain: {
      what: 'Operating cash flow minus capital spending — the cash the business actually generated.',
      why: 'Profit can be accounting; FCF is spendable. It funds buybacks, dividends, and acquisitions.',
      good: 'Positive and near net income; FCF margin above 20% is strong.',
    },
  },
  {
    id: 'fcf-margin', label: 'FCF margin', family: 'cash', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'FCF margin' }, { kind: 'comparison', label: 'FCF margin' }],
    explain: {
      what: 'Free cash flow as a share of revenue.',
      why: 'Cash profitability in one number — how much of each sales dollar becomes free cash.',
      good: 'Above 20% is strong; above 40% is exceptional and rare outside software.',
    },
  },
  {
    id: 'capex', label: 'Capex', family: 'cash', visual: 'bar', higherIsBetter: null,
    sources: [{ kind: 'kpis', label: 'Capex' }],
    explain: {
      what: 'Cash spent on property and equipment — for hyperscalers, mostly data centers.',
      why: 'Capex IS the AI bet at cloud companies: spending today converts into cloud capacity and, eventually, revenue.',
      good: 'No universal good level — compare against operating cash flow; capex persistently above OCF needs outside funding.',
    },
  },
  // ---------------- Market behavior ----------------
  {
    id: 'beta', label: 'Beta', family: 'market', visual: 'scale', higherIsBetter: null,
    sources: [{ kind: 'kpis', label: 'Beta' }, { kind: 'comparison', label: 'Beta' }],
    explain: {
      what: 'How much the stock tends to move relative to the overall market (market = 1.0).',
      why: 'Volatility shorthand — high beta amplifies both rallies and selloffs.',
      good: 'Near 1.0 moves with the market; well above 1.0 means a wilder ride in both directions.',
    },
  },
  {
    id: 'range-52w', label: '52-week range position', family: 'market', visual: 'chips', higherIsBetter: null,
    sources: [{ kind: 'kpis', label: '52-week range position' }, { kind: 'comparison', label: '52-week range position' }],
    explain: {
      what: 'Where the current price sits between its 52-week low and high.',
      why: 'Context for momentum — near the high means the market is still bidding it up.',
      good: 'No good or bad level; it frames whether you are looking at strength or weakness.',
    },
  },
  // ---------------- Cloud & backlog ----------------
  {
    id: 'cloud-revenue', label: 'Cloud revenue', family: 'cloud', visual: 'bar', higherIsBetter: true,
    sources: [{
      kind: 'kpis',
      perTicker: {
        MSFT: 'Azure revenue', AMZN: 'AWS revenue', GOOGL: 'Google Cloud revenue', Oracle: 'OCI revenue',
      },
    }],
    explain: {
      what: 'Revenue from the company’s cloud platform (Azure, AWS, Google Cloud, OCI).',
      why: 'Cloud is the highest-growth, highest-margin engine at the hyperscalers — its growth rate sets the stock narrative.',
      good: 'Double-digit growth; the market watches for acceleration versus deceleration quarter to quarter.',
    },
  },
  {
    id: 'ai-revenue', label: 'AI / data-center revenue', family: 'cloud', visual: 'bar', higherIsBetter: true,
    sources: [{
      kind: 'kpis',
      perTicker: {
        NVDA: 'Data center revenue', AMD: 'Data center revenue', INTC: 'DCAI revenue',
        AVGO: 'AI semi revenue (Q4)', MRVL: 'Data center revenue',
      },
    }],
    explain: {
      what: 'Revenue from AI accelerators and data-center silicon.',
      why: 'The AI buildout line — this is where the capex supercycle shows up as someone’s sales.',
      good: 'Growing multiples of the company average; heavy concentration here is both engine and risk.',
    },
  },
  {
    id: 'backlog', label: 'Backlog (RPO)', family: 'cloud', visual: 'bar', higherIsBetter: true,
    sources: [{
      kind: 'kpis',
      perTicker: {
        MSFT: 'Remaining performance obligations', AMZN: 'Remaining performance obligations',
        GOOGL: 'Remaining performance obligations', Oracle: 'Remaining performance obligations',
        CRWV: 'Revenue backlog',
        ANET: 'Remaining performance obligations',
        ASML: 'Remaining performance obligations',
        CIEN: 'Remaining performance obligations',
        CRM: 'Remaining performance obligations',
        CRWD: 'Remaining performance obligations',
        CSCO: 'Remaining performance obligations',
        DDOG: 'Remaining performance obligations',
        FIX: 'Remaining performance obligations',
        FTNT: 'Remaining performance obligations',
        GEV: 'Remaining performance obligations',
        HPE: 'Remaining performance obligations',
        IREN: 'Remaining performance obligations',
        LRCX: 'Remaining performance obligations',
        MDB: 'Remaining performance obligations',
        NET: 'Remaining performance obligations',
        NOW: 'Remaining performance obligations',
        OKTA: 'Remaining performance obligations',
        PANW: 'Remaining performance obligations',
        PLTR: 'Remaining performance obligations',
        PWR: 'Remaining performance obligations',
        S: 'Remaining performance obligations',
        SNDK: 'Remaining performance obligations',
        SNOW: 'Remaining performance obligations',
        TEAM: 'Remaining performance obligations',
        TER: 'Remaining performance obligations',
        TWLO: 'Remaining performance obligations',
        ZS: 'Remaining performance obligations'
      },
    }],
    explain: {
      what: 'Contracted revenue not yet recognized — sales already won, to be delivered later.',
      why: 'Visibility into future revenue; rising backlog means demand is outpacing delivery.',
      good: 'Growing faster than revenue is the strong setup; check contract durations behind the number.',
    },
  },
  // ---------------- Company-specific ----------------
  {
    id: 'ebitda-adj', label: 'Adjusted EBITDA', family: 'company', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Adjusted EBITDA' }],
    explain: {
      what: 'Earnings before interest, taxes, depreciation and amortization, adjusted for one-offs.',
      why: 'A rough proxy for operating cash earnings that strips out financing and accounting choices.',
      good: 'Compare as a margin against revenue; rising EBITDA margin signals operating leverage.',
    },
  },
  {
    id: 'rl-loss', label: 'Reality Labs loss', family: 'company', visual: 'bar', higherIsBetter: false,
    sources: [{ kind: 'kpis', label: 'Reality Labs loss' }],
    explain: {
      what: 'Meta’s reported operating loss on Reality Labs (VR/AR).',
      why: 'Quantifies the metaverse bet’s drag on Meta’s otherwise high-margin business.',
      good: 'Shrinking losses signal discipline; the market mostly wants the number contained.',
    },
  },
  {
    id: 'royalty', label: 'Royalty revenue', family: 'company', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Royalty revenue' }],
    explain: {
      what: 'Fees Arm collects per chip shipped using its designs.',
      why: 'Near-pure-margin revenue that scales with the entire chip industry’s volume.',
      good: 'Growing with chip shipments; royalty rate expansion comes from newer, richer architectures.',
    },
  },
  {
    id: 'licensing', label: 'Licensing revenue', family: 'company', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Licensing revenue' }],
    explain: {
      what: 'Upfront fees for the right to use Arm’s chip designs.',
      why: 'Lumpy but leading — big license deals today become royalty streams years later.',
      good: 'Strength here previews future royalty growth.',
    },
  },
  {
    id: 'chips-shipped', label: 'Chips shipped', family: 'company', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Chips shipped' }],
    explain: {
      what: 'Number of chips shipped using Arm’s designs in the period.',
      why: 'Volume under the royalty model — the installed base future royalties are calculated on.',
      good: 'Steady growth in units; mix shifting toward higher-royalty designs matters more than raw units.',
    },
  },
  {
    id: 'foundry-rev', label: 'Foundry revenue', family: 'company', visual: 'bar', higherIsBetter: true,
    sources: [{ kind: 'kpis', label: 'Foundry revenue' }],
    explain: {
      what: 'Revenue from Intel’s contract chipmaking business.',
      why: 'The turnaround metric — external foundry customers validate the manufacturing bet.',
      good: 'Growing external (non-Intel) customer revenue; losses narrowing toward breakeven.',
    },
  },
]

/* ------------------------------------------------------------------ */
/* Resolution — figures come from the datasets, never from this file    */
/* ------------------------------------------------------------------ */

function figureFromKpis(ticker, label) {
  const rec = kpisByTicker[ticker]
  if (!rec) return null
  const m = rec.metrics.find((x) => x.label === label)
  if (!m || m.value == null) return null
  return { value: m.value, sub: m.sub || '', tier: m.tier, source: rec.source, asOf: rec.asOf }
}

function figureFromComparison(ticker, label) {
  for (const fam of comparison.families || []) {
    const m = (fam.metrics || []).find((x) => x.label === label)
    if (!m) continue
    const fig = ticker === 'NVDA' ? m.nvda : ticker === 'AMD' ? m.amd : null
    if (fig && fig.value != null) return { ...fig, reading: m.reading, explain: m.explain, stronger: m.stronger }
  }
  return null
}

/** Resolve one metric for one ticker → figure object or null. */
export function resolveFigure(metricId, ticker) {
  const def = METRICS.find((m) => m.id === metricId)
  if (!def) return null
  for (const s of def.sources) {
    if (s.kind === 'kpis') {
      const label = s.perTicker ? s.perTicker[ticker] : s.label
      if (!label) continue
      const fig = figureFromKpis(ticker, label)
      if (fig) return { ...fig, metricId, ticker }
    } else if (s.kind === 'comparison') {
      const fig = figureFromComparison(ticker, s.label)
      if (fig) return { ...fig, metricId, ticker }
    }
  }
  return null
}

/** How many of the given tickers have data for this metric. */
export function coverage(metricId, tickers) {
  return tickers.filter((t) => resolveFigure(metricId, t) != null).length
}

/** Metrics with ≥1 company holding data — the only ones the picker may show. */
export function availableMetrics(allTickers) {
  return METRICS.filter((m) => coverage(m.id, allTickers) > 0)
}

/* ------------------------------------------------------------------ */
/* Generated 4th explanation layer + takeaways (deterministic)          */
/* ------------------------------------------------------------------ */

function ratioText(vals) {
  const nums = vals.map((v) => parseScalar(v)).filter((n) => n != null && n > 0)
  if (nums.length < 2) return ''
  const mx = Math.max(...nums)
  const mn = Math.min(...nums)
  if (mn <= 0) return ''
  const r = mx / mn
  return r >= 1.5 ? ` — a ${r >= 10 ? Math.round(r) : r.toFixed(1)}× spread` : ''
}

/** "What this result means" generated from the live selection. */
export function describeGap(def, figs) {
  const withVal = figs.filter((f) => f && f.value != null)
  if (withVal.length === 0) return 'No figures available for the selected companies.'
  const scored = withVal
    .map((f) => ({ f, n: parseScalar(f.value) }))
    .filter((s) => s.n != null)
  if (scored.length === 0) {
    return `${withVal.map((s) => `${s.ticker} ${s.value}`).join(' · ')}.`
  }
  const desc = def.higherIsBetter === false
  const sorted = [...scored].sort((a, b) => (desc ? a.n - b.n : b.n - a.n))
  const lead = sorted[0]
  const tail = sorted[sorted.length - 1]
  if (sorted.length === 1) {
    return `${lead.f.ticker} reports ${lead.f.value}. No peer selected for comparison.`
  }
  const spread = ratioText(scored.map((s) => s.f.value))
  return `${lead.f.ticker} leads at ${lead.f.value} vs ${tail.f.ticker} ${tail.f.value}${spread}.`
}

/** Top-3 biggest relative gaps across the selected metrics — hero callouts. */
export function topTakeaways(metricIds, tickers) {
  const scored = []
  for (const id of metricIds) {
    const def = METRICS.find((m) => m.id === id)
    if (!def || def.higherIsBetter == null) continue
    const figs = tickers.map((t) => resolveFigure(id, t)).filter(Boolean)
    const nums = figs.map((f) => ({ f, n: parseScalar(f.value) })).filter((s) => s.n != null && s.n > 0)
    if (nums.length < 2) continue
    const mx = Math.max(...nums.map((s) => s.n))
    const mn = Math.min(...nums.map((s) => s.n))
    if (mn <= 0 || mx / mn < 1.5) continue
    const lead = nums.reduce((a, b) => (def.higherIsBetter === false ? (a.n < b.n ? a : b) : (a.n > b.n ? a : b)))
    scored.push({ def, lead, ratio: mx / mn })
  }
  scored.sort((a, b) => b.ratio - a.ratio)
  return scored.slice(0, 3).map(({ def, lead, ratio }) => ({
    figure: lead.f.value.split(' ')[0],
    sub: `${def.label} — ${lead.f.ticker} leads${ratio >= 10 ? ` by ${Math.round(ratio)}×` : ` (${ratio.toFixed(1)}× spread)`}`,
  }))
}
